/* 
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <stdio.h>
#include <time.h>



int divisors(long int*p){
	int count = 0;
	for(int i = 1; i*i <= *p; i++)
		if( !(*p % i) )
			count++;

	return 2*count;
}

int main(int argc, char const *argv[])
{
	long int triangularNumber = 1;
	int n = 1;
	clock_t begin, end;

	begin = clock();

	while(divisors(&triangularNumber) < 500){
		n++;
		triangularNumber += n;

		/* 	Original solution before otpimizing my code:
			triangularNumber = 0;
			for(int i = 0; i <= n; i++)
				triangularNumber += i;
		*/
	}

	end = clock();

	printf("%dth triangular Number: %ld\n", n, triangularNumber);
	printf("Divisors: %d\n", divisors(&triangularNumber));
	
	printf("Duration: %f\n", (double)(end - begin) / CLOCKS_PER_SEC);

	return 0;
}